package pl.edu.pjwstk.project.services;

import java.sql.*;

public final class DBmanager {

	private Connection connection;
	private Statement statement;
	private String url="jdbc:hsqldb:hsql://localhost/workdb";
	private ResultSet rs;
	private String createTable=
			"CREATE TABLE Planes(id bigint GENERATED BY DEFAULT AS IDENTITY," +
					" name varchar(20), tailnumber int, capacity int, passengers int," +
					"destination varchar(20), readytogo boolean))";
	private String addPlaneSQL="";
	private String removePlaneSQL="";
	private String getAllSQL="";
	private String addPassengerSQL="";
	
	
	PreparedStatement addPlane;
	PreparedStatement removePlane;
	PreparedStatement getAll;
	PreparedStatement addPassenger;
	PreparedStatement removePassenger;
	PreparedStatement removeAllPasssengers;

	private DBmanager() {
		try {
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();

			rs = connection.getMetaData().getTables(null, null, null,
			null);
			
			addPlane=connection.prepareStatement("");
			removePlane=connection.prepareStatement("");
			getAll=connection.prepareStatement("");
			addPassenger=connection.prepareStatement("");
			removePassenger=connection.prepareStatement("");
			removeAllPasssengers=connection.prepareStatement("");
			
			} catch (SQLException e) {
			e.printStackTrace();
			}
	
	}

	private static DBmanager instance;

	public static DBmanager getInstance() {

		if (instance == null)
			synchronized (DBmanager.class) {
				if (instance == null)
					instance = new DBmanager();
			}
		return instance;
	}
	
	
	//metody
	
	void addPlaneToDB(){
		
	}
	
	
	
}